### ISSUE TITLE
Mistery packages to document

### ISSUE THREAD

**Issue by ohault** [microsoft/azurelinux#10996]
Some mystery binary files are currently available for Azure Linux 3.0 on the following URL

https://packages.microsoft.com/azurelinux/3.0/prod/ms-non-oss/

I wonder the following :
- Could you document these packages ?
- how to install them, especially for bare metal ?
- why some of them would look like containing "Windows" PE files ?
- what is Hyper-V 2.0 ?
- if it is used for Confidential Computing, where are the source of these packages ?

**Comment by zcobol** [comment]
@ohault `ms-non-oss` is `Microsoft non Open Source Software` and if you look inside the RPMs there is indeed MS proprietary code!

**Comment by eric-desrochers** [comment]
ms-non-oss in `3.0` (formerly known as extras in `2.0`) is a repository for closed-source Microsoft software.
It's an repo enabled by default and package found in there can be install like any other RPM package.

**Comment by ohault** [comment]
Hi @eric-desrochers , thank you for the explanation, I have rename the title of this issue accordingly. Before closing this issue, these non-oss packages still need to be documented as for https://github.com/microsoft/azurelinux/issues/6427 and https://github.com/microsoft/azurelinux/issues/6937

**Comment by olljanat** [comment]
> https://packages.microsoft.com/azurelinux/3.0/prod/ms-non-oss/
> * why some of them would look like containing "Windows" PE files ?

Documenting here as I found answer. They look Windows PE files, because they are exactly same Hyper-V binaries which are used in Windows. This can be proven by downloading preview version of Windows Server 2025 with ISO name `26100.1.240331-1435.ge_release_SERVER_EVAL_x64FRE_en-us.iso` and `mshv-26100.1.240331-1435.1.x86_64.rpm` (only combination which I found with exact same build number):
<img width="1088" height="508" alt="Image" src="https://github.com/user-attachments/assets/a7f35907-09d9-464d-8263-468dbc780a81" />

The actual new Linux based things are:
* [HvLoader.efi](https://github.com/microsoft/HvLoader)
* `lxhvloader.dll` which comes from `mshv-bootloader-lx-...` RPM packages and which is actually only Linux specific binary which Microsoft has build which is not available as open source.
* Kernel drivers providing `/dev/mshv` device access which #6427 is about.

That approach is smart as there is no need to have separate Hyper-V binaries for Linux and Windows.

> ms-non-oss in `3.0` (formerly known as extras in `2.0`) is a repository for closed-source Microsoft software. It's a repo enabled by default and packages found in there can be installed like any other RPM package.

@eric-desrochers Now when also QEMU has support for mshv accelerator it would be nice to get clarity of licensing of Linux on Hyper-V. Does same CPU core based terms apply than to Windows version? How to apply to be early adopter for on-prem deployment (I would assume that this does not go under Windows insider)?

**Comment by ohault** [comment]
The recent FOSDEM 2026 presentation of [MSHV accelerator in QEMU](https://fosdem.org/2026/schedule/event/BFQ8XA-introducing-mshv-accelerator-in-qemu/) by @mkulke brings more information about this, and I guess OpenVMM/openHCL - https://openvmm.dev/guide/.

A clear roadmap would be highly appreciated (both of x64 and arm64), and from a cybersecurity perspective, along with comprehensive documentation detailing how Microsoft currently leverages Hyper-V with a Linux based root partition in certain products

**Comment by mkulke** [comment]
@ohault I think the above packages are related to a nested hypervisor with mshv + cloud-hypervisor, used by kata containers in the "AKS Pod Sandbox" product: https://learn.microsoft.com/en-us/azure/aks/use-pod-sandboxing#how-it-works

I'm not 100% sure, though, I asked a colleague to clarify.

meanwhile, the development of the MSHV kernel driver and QEMU accelerator happens in the upstream projects, that would be the lkml (linux-hyperv) and qemu-devel (accel/mshv subsystem).

**Comment by olljanat** [comment]
@mkulke yes, license files inside of those packages clearly says that they are related to AKS. However, they are currently only way how people outside of Microsoft can get access to MSHV binaries.

> meanwhile, the development of the MSHV kernel driver and QEMU accelerator happens in the upstream projects, that would be the lkml (linux-hyperv) and qemu-devel (accel/mshv subsystem).

In your presentation you mentioned that Baremetal deployment is yet in mainline kernel. So what exactly is still missing?

mshv kernel for Azure Linux contains [this](https://github.com/microsoft/azurelinux/blob/6884968e5a7e10304d9709f99528e120ed5cf6ec/SPECS/kernel-mshv/50_mariner_mshv_menuentry) script which generates MSHV boot entry and that already can boot mainline kernel just fine.
<img width="455" height="192" alt="Image" src="https://github.com/user-attachments/assets/912dd5dc-d068-4cec-b5cf-79447a470bf7" />

But from `Hyper-V: privilege flags` prints in dmesg we see that it does not get same privileges than Azure Linux MSHV kernel and as result of that loading of `mshv_root` module fails.

`lxhvloader.dll` also seems to accept parameters like these `MSHV_DEBUG_ENABLED=1 MSHV_DEBUG_TYPE=SERIAL MSHV_DEBUG_PORT=1 MSHV_DEBUG_BAUD_RATE=115200`
<img width="227" height="57" alt="Image" src="https://github.com/user-attachments/assets/9f1b055e-c290-4808-a234-719cb8f91334" />
but I cannot make it connect to WinDbg so perhaps there is still some more step needed?

**Comment by mkulke** [comment]
> > meanwhile, the development of the MSHV kernel driver and QEMU accelerator happens in the upstream projects, that would be the lkml (linux-hyperv) and qemu-devel (accel/mshv subsystem).
> 
> In your presentation you mentioned that Baremetal deployment is yet in mainline kernel. So what exactly is still missing?

I think the easiest option to reproduce/understand what's happening on the AKS kata images is to grab a kernel config from such an AKS worker node and then build your Azure own kernel from sources according to the [documentation](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/tree/docs) (the tag you need to build from should include "kata", so it'll have recent drivers/hv/mshv* code).

nb: the only scenario for which code is currently being upstreamed into the mainline kernel is "Direct Virtualization". That means: a Linux host is an L1VH, a Virtual Host running as L1 VM on Microsoft Hypervisor (i.e. not a root partition). This host is able to spawn virtual L2 guests (= L1 siblings), that receive sub-partitioned resources from the L1VH. For the other 2 options (root partition on either a nested or baremetal hypervisor) you would need to bundle (non-oss) hypervisor binaries, which are subject to special licensing terms, like in those AKS images.

**Comment by olljanat** [comment]
I see both L1VH and root partition support in mainline code: https://github.com/torvalds/linux/blob/6de23f81a5e08be8fbf5e8d7e9febc72a5b5f27f/drivers/hv/hv_common.c#L742-L767

But what I mean is that it is parsed based on privilege flags checked in: https://github.com/torvalds/linux/blob/6de23f81a5e08be8fbf5e8d7e9febc72a5b5f27f/arch/x86/kernel/cpu/mshyperv.c#L522-L533

When booting with Azure Linux MSHV kernel these flags are visible:
```
Hyper-V: privilege flags low 0x2fff, high 0x2bb9ff, ext 0x222, hints 0x963d3c, misc 0x60fef7f2
```
When booting with mainline kernel only these are visible:
```
Hyper-V: privilege flags low 0xae7f, high 0x3b8030, ext 0x22, hints 0x9e6e24, misc 0xe0bed7b2
```
when boot parameters are same.

So for me it looks that there is some hidden check inside of `lxhvloader.dll` which decides which privilege flags are granted depending which kernel binary it loads but it is not signature check because it works fine when if build Azure Linux kernel from [rolling-lts/kata/6.6.100.mshv1](https://github.com/microsoft/CBL-Mariner-Linux-Kernel/tree/rolling-lts/kata/6.6.100.mshv1) tag.

**Comment by olljanat** [comment]
> So for me it looks that there is some hidden check inside of `lxhvloader.dll` which decides which privilege flags are granted depending which kernel binary it loads

Found it. Root partition support seems to be already in mainline kernel but EFI stub updates are not. Rebased those commits to https://github.com/olljanat/linux/commit/4266b0011469b4cc7efd436c76861f2e9f8adbc1 which with kernel 7.0-rc1 gets needed privileges and prints `Hyper-V: running as root partition` in boot (but it needs to be running in actual hardware as nested virtualization support is missing some parts).

**Comment by ohault** [comment]
Thank you, any updates according to the release of Linux kernel 7.0 ?

**Comment by olljanat** [comment]
I don’t see any efforts about upstreaming those EFI changes in lkml.org so need custom kernel with above patch included.

Ubuntu 26.04 however seems to be released with kernel 7.0 so perhaps easiest solution would be to create open source project which provides linux-hyperv kernel for it. It is LTS version so these parts of code shouldn’t change so releasing of those kernels can be automated.

Same project can also provide Hyper-V package for Ubuntu. License terms does not allow anyone else than Microsoft distribute those binaries so it need to be Deb package which contains just install and update scripts which fetches those from Azure Linux repo.

Anyone interested about solution like that can leave 🚀 reaction to this message. I can potentially create that if there is enough interest.

**Comment by ohault** [comment]
It will be amazing.

**Comment by olljanat** [comment]
I asked Claude to build it and seems that with small changes to seems to pass building.
However there is some things which needs still fixing before binaries can be published so I created tracking issues about those.

Project is available in https://github.com/olljanat-ai/hyperv-for-linux and contributions are welcome.

**Comment by ohault** [comment]
> I asked Claude to build it and seems that with small changes to seems to pass building.
> However there is some things which needs still fixing before binaries can be published so I created tracking issues about those.
> 
> Project is available in https://github.com/olljanat-ai/hyperv-for-linux and contributions are welcome.

Do you think you could try to fix the last issues?

**Comment by olljanat** [comment]
Issue tracker exists in there so will not comment more in here but as far I remember there is at least one open PR waiting for testers.

And overall that project needs contributors with real use cases.
