### ISSUE TITLE
tdnf is sometimes hanging on update and install

### ISSUE THREAD

**Issue by sirredbeard** [microsoft/azurelinux#8431]
**Describe the bug**

Running `sudo tdnf update` is hanging or getting killed. _Sometimes_.

**To Reproduce**

1. Install Mariner 2.0 in Hyper-V Gen2 VM.
2. Run `sudo tdnf update`

**Expected behavior**

tdnf updates.

**Screenshots**

![image](https://github.com/microsoft/azurelinux/assets/33820650/ac5057a7-9382-4d28-b407-b8582071ee86)

**Possible related**

This may or may not be related, but currently attempting to do the same on the WSL system distro results in:

![image](https://github.com/microsoft/azurelinux/assets/33820650/9060072f-9d13-4793-a809-1b600f8750a9)

However, after restart of the Hyper-V VM, it seems to be working okay now. Opening issue for possible investigation.

**Comment by anphel31** [comment]
I'm not sure about the timeout with the `tdnf update` command - it seems to be an issue with the repo/server.

The second error mentioned `Error(1261) : SSL peer certificate or SSH remote key was not OK` is caused by a new certificate being used on the packages.microsoft.com server, which is not available in our old certificate bundle. You'll need to ensure your image has version `ca-certificates-2.0.0-14.cm2` or newer in order to connect.
