### ISSUE TITLE
drop 0007-feat-dracut.sh-support-multiple-config-dirs.patch

### ISSUE THREAD

**Issue by LaszloGombos** [microsoft/azurelinux#9543]
Would you consider dropping https://github.com/microsoft/azurelinux/blob/3.0-dev/SPECS/dracut/0007-feat-dracut.sh-support-multiple-config-dirs.patch ?

This was introduced in Photon OS, not sure if it is still needed for azurelinux.

If there is a good use-case we can consider this change upstream, but perhaps this is no longer needed.

Earlier upstream discussion - https://github.com/dracutdevs/dracut/pull/2210 - but we can reopen this case upstream if needed .

CC @Camelron

**Comment by Camelron** [comment]
The upstream discussion is interesting because we were running into a similar dilemma with multiple kernel flavors (kernel, kernel-mshv) on the same system. Multiple confdirs ultimately couldn't help us however due to how initramfs generation integrates with our current packages/RPM scriptlets. 

Ultimately what we decided is that dracut configs make sense at the overall image level (where does the image need to boot...) rather than at the kernel granularity. Planning on dropping this one as well but will be thinking this decision over once more before doing so..

**Comment by Camelron** [comment]
Yea I think the scenario of supporting multiple kernel flavors on one image is not a realistic one. As a distro, we should favor shipping specific kernels on specific images for specific intended target platforms.

This feature is intended mainly for kernels which supply/support different sets of packages/features but this is not needed because above decision. Dropping the patch.

**Comment by Camelron** [comment]
Thanks for reporting this, we've dropped the patch. I'll keep an eye on the upstream discussion if this feature does end up merged though!
