### ISSUE TITLE
Add stress-ng package

### ISSUE THREAD

**Issue by goiri** [microsoft/azurelinux#9903]
Can we add `stress-ng` to the official packages?
Meanwhile:
```
sudo dnf install build-essential git htop binutils
git clone https://github.com/ColinIanKing/stress-ng.git
cd stress-ng
make
sudo make install
```

**Comment by ColinIanKing** [comment]
It is important to note that stress-ng will build with minimal dependencies but to ensure it is built with a full set of working stressors one should install all the recommended dependencies so that the build will autodetect these at build time,

See: https://github.com/ColinIanKing/stress-ng/blob/master/README.md

**Comment by mfrw** [comment]
Package added to 3.0-dev:
- https://github.com/microsoft/azurelinux/pull/10102
